# Generated by Django 3.2.4 on 2021-10-08 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import team_leader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0002_alter_reports_reportfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProjectMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messageTo', models.CharField(default='user', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('projectMessageFile', models.FileField(blank=True, upload_to='message_documents/', validators=[team_leader.models.validate_file], verbose_name='Message File')),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('isFirstMessage', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('messageSender', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Message From')),
                ('projectId', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='director.projects', verbose_name='Project ID')),
                ('projectUnique', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='director.projects', to_field='expertUnique')),
            ],
            options={
                'verbose_name_plural': 'Expert Project Messages',
            },
        ),
    ]
