# Generated by Django 3.2.4 on 2021-10-17 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import team_leader.models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_auto_20211017_0750'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20210930_1427'),
        ('team_leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('reportMessageFile', models.FileField(blank=True, upload_to='message_documents/', validators=[team_leader.models.validate_file], verbose_name='Message File')),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('isFirstMessage', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('messageSender', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Message From')),
                ('messageTo', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='authentication.teams', verbose_name='Message To')),
                ('reportId', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='director.reports', verbose_name='Report ID')),
            ],
            options={
                'verbose_name_plural': 'Team Report Messages',
            },
        ),
    ]
