# Generated by Django 3.2.4 on 2021-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0002_expertprojectmessages_projectunique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprojectmessages',
            name='messageTo',
            field=models.CharField(default='user', max_length=200, verbose_name='Message To'),
        ),
    ]
