# Generated by Django 3.2.4 on 2021-10-04 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_leader', '0003_alter_expertprojectmessages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprojectmessages',
            name='messageSender',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Message From'),
        ),
    ]
