# Generated by Django 3.2.4 on 2021-10-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_director', '0002_auto_20211008_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveReportTeam',
        ),
    ]
