# Generated by Django 3.2.4 on 2021-10-08 06:53

import director.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20210930_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectTitle', models.CharField(max_length=150, verbose_name='Project Title')),
                ('projectDescription', models.TextField(verbose_name='Project Description')),
                ('deadLine', models.DateField(verbose_name='Project DeadLine')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent')),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('assignToExperts', models.BooleanField(blank=True, default='False', null=True, verbose_name='Assign To Experts')),
                ('projectFile', models.FileField(blank=True, upload_to='project_documents/', validators=[director.models.validate_file], verbose_name='Project File')),
                ('teamUnique', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('expertUnique', models.UUIDField(blank=True, null=True, unique=True)),
                ('currentlyOn', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('directorApproved', models.BooleanField(default=False, verbose_name='Approve Project From Team Leader')),
                ('leaderApproved', models.BooleanField(default=False, verbose_name='Approve Project Submission From Experts')),
                ('directorApprovedDate', models.DateField(blank=True, default=None, null=True, verbose_name='Project Approved on')),
                ('leaderApprovedDate', models.DateField(blank=True, default=None, null=True)),
                ('is_late', models.BooleanField(blank=True, default=False, null=True)),
                ('assignedTeam', models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='authentication.teams', verbose_name='Assign Project to')),
                ('created_by', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project Created By')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TeamProjectMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('projectMessageFile', models.FileField(blank=True, upload_to='message_documents/', validators=[director.models.validate_file], verbose_name='Message File')),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('isFirstMessage', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('messageSender', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Message From')),
                ('messageTo', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message To')),
                ('projectId', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='director.projects', verbose_name='Project ID')),
                ('projectUnique', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='director.projects', to_field='teamUnique')),
            ],
            options={
                'verbose_name_plural': 'Team Project Messages',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportTitle', models.CharField(max_length=150, verbose_name='Report Title')),
                ('reportsDescription', models.TextField(blank=True, null=True, verbose_name='Report Description')),
                ('deadLine', models.DateField(verbose_name='Report DeadLine')),
                ('is_seen', models.BooleanField(default=False)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('reportFile', models.FileField(blank=True, upload_to='project_documents/', validators=[director.models.validate_file], verbose_name='Report File')),
                ('directorUnique', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('directorApproved', models.BooleanField(default=False, verbose_name='Approve Report From Assistant Director')),
                ('leaderApproved', models.BooleanField(default=False, verbose_name='Approve Report Submission From Experts')),
                ('assistantApproved', models.BooleanField(default=False, verbose_name='Approve Report Submission From Teams')),
                ('directorApprovedDate', models.DateField(blank=True, default=None, null=True, verbose_name='Report Approved on')),
                ('assistantApprovedDate', models.DateField(blank=True, default=None, null=True, verbose_name='Report approved from assistant director on')),
                ('leaderApprovedDate', models.DateField(blank=True, default=None, null=True)),
                ('is_late', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Report requested By')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='DirectorReportMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('reportMessageFile', models.FileField(blank=True, upload_to='message_documents/', validators=[director.models.validate_file], verbose_name='Message File')),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('isFirstMessage', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('messageSender', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Message From')),
                ('messageTo', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message To')),
                ('reportId', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='director.reports', verbose_name='Report ID')),
            ],
            options={
                'verbose_name_plural': 'Director Report Messages',
            },
        ),
    ]
