# Generated by Django 3.2.4 on 2021-10-04 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamProjectMessages',
            new_name='TemProjectMessages',
        ),
    ]
