# Generated by Django 3.2.4 on 2021-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Is Urgent'),
        ),
    ]
