# Generated by Django 3.2.4 on 2021-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_alter_projects_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assignedTeam',
            field=models.CharField(max_length=300, verbose_name='Assign Project to'),
        ),
    ]
