# Generated by Django 3.2.4 on 2021-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_rename_teamprojectmessages_temprojectmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='directorApprovedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='leaderApprovedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='directorApproved',
            field=models.BooleanField(default=False),
        ),
    ]
