# Generated by Django 3.2.4 on 2021-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_alter_projects_assignedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
