# Generated by Django 3.2.4 on 2021-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_auto_20211005_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='directorApproved',
            field=models.BooleanField(default=False, verbose_name='Approve Project From Team Leader'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='directorApprovedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Project Approved on'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='leaderApproved',
            field=models.BooleanField(default=False, verbose_name='Approve Project Submission From Expert'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectTitle',
            field=models.CharField(max_length=150, verbose_name='Project Title'),
        ),
    ]
