# Generated by Django 3.2.4 on 2021-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_auto_20211008_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='assistantApproved',
            field=models.BooleanField(default=False, verbose_name='Approve Report Submission From Teams'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='assistantApprovedDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Report approved from assistant director on'),
        ),
    ]
