# Generated by Django 3.2.4 on 2021-10-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210930_1427'),
        ('director', '0005_auto_20211002_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assignedTeam',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='authentication.teams', verbose_name='Assign Project to'),
        ),
    ]
