# Generated by Django 3.2.4 on 2021-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_auto_20211007_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='directorApprovedDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Project Approved on'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='leaderApprovedDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
