# Generated by Django 3.2.4 on 2021-10-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_auto_20211017_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='leaderApproved',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='leaderApprovedDate',
        ),
    ]
