# Generated by Django 3.2.4 on 2021-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_auto_20211007_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='assignedExpert',
        ),
        migrations.AddField(
            model_name='projects',
            name='assignToExperts',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Assign To Experts'),
        ),
    ]
