# Generated by Django 3.2.4 on 2021-10-03 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0006_alter_projects_assignedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='assignedExpert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Expert'),
        ),
    ]
