# Generated by Django 3.2.4 on 2021-10-04 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_projects_assignedexpert'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessages',
            name='projectUnique',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='currentlyOn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='expertUnique',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='teamUnique',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
