# Generated by Django 3.2.4 on 2021-10-04 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0008_auto_20211004_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMessages',
            new_name='TeamProjectMessages',
        ),
        migrations.AlterModelOptions(
            name='teamprojectmessages',
            options={'verbose_name_plural': 'Team Project Messages'},
        ),
    ]
