# Generated by Django 3.2.4 on 2021-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0009_auto_20211004_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='expertUnique',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
