# Generated by Django 3.2.4 on 2021-10-04 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0010_auto_20211004_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='teamUnique',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
