# Generated by Django 3.2.4 on 2021-09-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.roles', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, default=1, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teams', verbose_name='Team'),
        ),
    ]
